// Английский перевод интерфейса и установщика: русский текст → английский.
// Склонения (plural): ключ — первая русская форма, значение — «один|много».
// Полнота проверяется `npm run i18n`.

export const en: Record<string, string> = {
  // Рамка окна
  "Свернуть": "Minimize",
  "Свернуть в трей": "Minimize to tray",
  "Главная": "Home",
  "Соединение": "Connection",
  "Добавить": "Add",
  "Настройки": "Settings",
  "Разделы": "Sections",
  "Служба kl!ck не отвечает": "The kl!ck service is not responding",
  "Окно работает, но без службы VPN не включить. Переустановите kl!ck или перезагрузите компьютер.": "The window is running, but VPN can't be turned on without the service. Reinstall kl!ck or restart your computer.",
  "Тестовая служба недоступна.": "The test service is unavailable.",
  // Kill Switch: как работает
  "Как работает Kill Switch": "How Kill Switch works",
  "VPN включён": "VPN on",
  "VPN выключен": "VPN off",
  "Защищённые": "Protected",
  "{n} в списке": "{n} on the list",
  "Остальные": "Everything else",
  "по тумблеру": "per the switch",
  "приложения": "apps",
  "Провайдер": "ISP",
  "Интернет": "Internet",
  "сайты": "websites",
  "Защищённые программы ходят только через VPN — даже если тумблер пустил бы их напрямую. Остальные — как решает тумблер: сейчас «{routing}».": "Protected apps go only through VPN, even if the switch would send them directly. Everything else follows the switch: now “{routing}”.",
  "Защищённые программы остаются без интернета — их данные не уйдут через провайдера. Остальные работают напрямую.": "Protected apps stay offline, so their data won't go out through your ISP. Everything else works directly.",
  "Локальная сеть для них открыта: роутер, принтер, игры по локалке.": "The local network stays open for them: router, printer, LAN games.",
  "Понятно": "Got it",
  // Живая схема
  "пока никого": "nothing yet",
  "Компьютер": "Computer",
  "программа": "app|apps",
  "Напрямую": "Direct",
  "через VPN": "via VPN",
  "напрямую": "direct",
  "блок": "blocked",
  "В режиме системного прокси видны только программы, которые идут через прокси.": "In system proxy mode, only apps that use the proxy are shown.",
  "VPN выключен: всё идёт напрямую. Схема оживёт после подключения.": "VPN is off: everything goes directly. The diagram comes alive once you connect.",
  // Выбор программ
  "Поиск по названию или .exe": "Search by name or .exe",
  "Запущено сейчас": "Running now",
  "по сетевой активности": "by network activity",
  "Смотрю, кто в сети…": "Checking what is online…",
  "Ничего не найдено": "Nothing found",
  "Программа не запущена? Выберите её .exe вручную через «Обзор…».": "App not running? Pick its .exe manually with “Browse…”.",
  "в общей папке — перенесите в свою": "in a shared folder — move it to its own",
  "уже в списке": "already on the list",
  // Схема переключения
  "трафик сейчас": "traffic now",
  "после переключения": "after switching",
  // Форматы
  "ГБ": "GB",
  "МБ": "MB",
  "{used} из {total} ГБ": "{used} of {total} GB",
  "нет ответа": "no response",
  "{n} мс": "{n} ms",
  // Правила
  "Яндекс Браузер": "Yandex Browser",
  "Система": "System",
  "Неизвестная программа": "Unknown app",
  "Через VPN": "Via VPN",
  "сайт и поддомены": "site and subdomains",
  "вся зона": "whole zone",
  "адрес": "address",
  "подсеть": "subnet",
  // Диалоги
  "Выберите программу": "Choose an app",
  "Программы": "Programs",
  // Темы
  "Графит": "Graphite",
  "Полночь": "Midnight",
  "Светлая": "Light",
  "Системная": "System",
  "Тёмная": "Dark",
  "Своя": "Custom",
  "Повторяет тему Windows и переключается вместе с ней.": "Follows the Windows theme and switches with it.",
  "Светлый фон и тёмный текст — удобно при ярком освещении.": "Light background and dark text — comfortable in bright light.",
  "Тёмный фон — меньше нагрузки на глаза вечером.": "Dark background — easier on the eyes in the evening.",
  "Выберите основу и цвет акцента ниже.": "Pick a base and an accent color below.",
  // Установщик: диалоги
  "Папка для kl!ck": "Folder for kl!ck",
  // Сообщения
  "Подключено к {name}": "Connected to {name}",
  "Подключено": "Connected",
  "Подписка обновлена": "Subscription updated",
  "Список серверов и лимиты актуальны": "Server list and limits are up to date",
  "Подключение удалено": "Connection removed",
  "Подключение добавлено": "Connection added",
  "Проверьте задержку серверов": "Check server latency",
  "Файл импортирован": "File imported",
  "Kill Switch выключен": "Kill Switch is off",
  "Программы из списка пойдут напрямую без VPN": "Apps on the list will go directly, without VPN",
  "Отменить": "Undo",
  "Программа убрана из Kill Switch": "App removed from Kill Switch",
  "Правило удалено": "Rule removed",
  "Правило в «{position} · мой список»": "Rule added to “{position} · my list”",
};
