[package]
name = "klick-cli"
description = "Утилита для проверки службы kl!ck без окна"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
klick-core.workspace = true
klick-proto.workspace = true
serde_json.workspace = true
anyhow.workspace = true
tokio.workspace = true
clap.workspace = true
